import Link from "next/link";

const facts = [["4","RRT-family planners"],["20","simulation seeds"],["260","dynamic frames"],["120","planning steps per frame"]];

export default function MotionPlanningPage() {
  return (
    <main className="case motion-case">
      <header className="case-hero shell">
        <div className="case-title"><Link className="back-link" href="/projects">← All projects</Link><p className="eyebrow">Master of Engineering · 2026</p><h1>Dynamic Robot Motion Planning</h1><p>A comparative evaluation of RRT-based replanning in changing environments, supported by controlled simulation and physical validation.</p></div>
        <figure className="case-film"><video autoPlay muted loop playsInline preload="auto" poster="/motion-planning/planner-snapshots.jpg" aria-label="Four motion planners adapting paths as obstacles move"><source src="/motion-planning/planner-comparison.mp4" type="video/mp4" /></video><figcaption><span>RRT</span><span>RRT-Connect</span><span>RRT*</span><span>RRTX</span><strong>Four planners under the same dynamic scenario</strong></figcaption></figure>
      </header>

      <section className="case-overview shell"><div><p className="eyebrow">System developed</p><h2>One framework for measuring how planners adapt.</h2></div><div><p>The project placed four sampling-based planners inside a common discrete-time replanning loop. Each received the same start, goal, occupancy map, obstacle updates, and computational budget so differences in speed, path quality, clearance, and replanning burden could be compared fairly.</p><div className="scope-tags"><span>Motion planning</span><span>Computer vision</span><span>Simulation</span><span>Calibration</span><span>Data analysis</span></div></div></section>

      <section className="story shell">
        <header className="story-head"><p className="eyebrow">Project storyline</p><h2>From planner theory to a live projected path.</h2></header>

        <article className="story-step"><div className="step-number">01</div><div className="step-copy"><span>Frame the comparison</span><h3>Evaluate adaptation, not just first-path generation.</h3><p>The environment changed frame by frame. A previously valid route could become blocked, forcing each planner to continue growing, reset and replan, or repair its existing structure. The study measured both planning effectiveness and the cost of adaptation.</p></div><div className="planner-stack"><div><strong>RRT</strong><span>Exploratory baseline</span></div><div><strong>RRT-Connect</strong><span>Bidirectional search</span></div><div><strong>RRT*</strong><span>Path refinement</span></div><div><strong>RRTX</strong><span>Repair-oriented replanning</span></div></div></article>

        <article className="story-step"><div className="step-number">02</div><div className="step-copy"><span>Build a common loop</span><h3>Give every planner the same representation and budget.</h3><p>Both the physical and simulated systems reduced their environment to a 2D occupancy mask. The planner received a start state, goal state, map dimensions, and obstacle mask, then expanded its search structure for a fixed budget before the next update.</p></div><div className="system-flow motion-flow"><span>Observe environment</span><i>→</i><span>Build occupancy mask</span><i>→</i><span>Update planner</span><i>→</i><span>Log performance</span></div></article>

        <article className="story-step"><div className="step-number">03</div><div className="step-copy"><span>Validate physically</span><h3>Connect perception, planning, and projection.</h3><p>A top-down camera detected the start marker, goal marker, and warehouse-style obstacles using color-based segmentation. Camera-projector calibration mapped computed paths back onto the physical surface as a live overlay.</p></div><div className="media-grid physical-grid"><figure className="media"><img src="/motion-planning/physical-workspace.jpg" alt="Physical workspace with projected paths and warehouse-style obstacles" /><figcaption>Projected planning workspace</figcaption></figure><figure className="media"><img src="/motion-planning/overhead-camera.jpg" alt="Overhead camera and projector used for physical validation" /><figcaption>Top-down sensing</figcaption></figure><figure className="media"><img src="/motion-planning/calibration-grid.jpg" alt="Camera-projector dot calibration process" /><figcaption>Projection calibration</figcaption></figure></div></article>

        <article className="story-step"><div className="step-number">04</div><div className="step-copy"><span>Benchmark in simulation</span><h3>Control the environment for repeatable comparison.</h3><p>The benchmark used a 1000 × 700 workspace, three moving obstacles, 260 frames, and 120 planning steps per frame. Twenty random seeds produced averaged metrics while a synchronized four-panel view made the evolving search structures visible.</p></div><div className="media-grid simulation-media"><figure className="media"><video autoPlay muted loop playsInline preload="metadata" poster="/motion-planning/planner-snapshots.jpg"><source src="/motion-planning/planner-comparison.mp4" type="video/mp4" /></video><figcaption>Dynamic four-planner comparison</figcaption></figure><figure className="media light contain"><img src="/motion-planning/simulation-frame.jpg" alt="Representative simulation frame with moving obstacles and planned path" /><figcaption>Common simulation environment</figcaption></figure></div></article>

        <article className="story-step"><div className="step-number">05</div><div className="step-copy"><span>Measure the tradeoffs</span><h3>Fast solutions and short paths came from different planners.</h3><p>RRT, RRT-Connect, and RRT* each solved all 20 simulation seeds. RRT-Connect reached feasible solutions fastest. RRT* produced the shortest average paths, but required substantially more planning time and more replanning events.</p></div><div className="result-board"><div><strong>6,095 ms</strong><span>RRT-Connect average first solution</span></div><div><strong>975 px</strong><span>RRT* average path length</span></div><div><strong>10.19 px</strong><span>RRT average minimum clearance</span></div><figure><img src="/motion-planning/path-length.png" alt="Average planned path length comparison" /></figure></div></article>

        <article className="story-step"><div className="step-number">06</div><div className="step-copy"><span>Interpret the result</span><h3>The best planner depends on the objective and environment.</h3><p>RRT-Connect was strongest for rapid feasible replanning. RRT* was strongest when path refinement justified extra computation. RRT remained a reliable baseline with greater average clearance. RRTX highlighted how strongly repair-based behavior can depend on the way environmental change is represented.</p></div><div className="media-grid result-charts"><figure className="media light contain"><img src="/motion-planning/first-solution-time.png" alt="Average time to first solution by planner" /></figure><figure className="media light contain"><img src="/motion-planning/replans.png" alt="Average number of replans by planner" /></figure></div></article>
      </section>

      <section className="facts shell">{facts.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section className="credits shell"><div><span>Team</span><p>George Mikhaiel · Aaron Emmanuel · Muhammad Saad Farooq Hamirani · Sheik (Farhaan) Elaheebocus</p></div><div><span>Course</span><p>Robot Motion Planning · Professor Jonathan Kelly</p></div></section>
      <nav className="case-next shell"><Link href="/projects/asl-glove">← Previous project · ASL Glove</Link><Link href="/projects">Project library</Link></nav>
    </main>
  );
}
